package selenium;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;

public class Selenium {

	private WebDriver driver;

	private Map<String, Object> vars;

	JavascriptExecutor js;

	final static String APPLICATION_BASE_URL = "https://gbsgit.edst.ibm.com";

	@Before
	public void setUp() {

		ChromeOptions options = new ChromeOptions();
		options.addArguments("--remote-allow-origins=*");
		options.addArguments("headless");
		driver = new ChromeDriver(options);
		driver.get(APPLICATION_BASE_URL);
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		//driver.quit();
		if (driver != null) {
			// LogUtil.setLogString("Quit driver for new browser", true);
			driver.quit();
		}
	}

	@Test
	public void alogin() {
    //driver.get("https://gbsgit.edst.ibm.com/users/sign_in");
    driver.manage().window().setSize(new Dimension(1050, 652));
    driver.findElement(By.linkText("Standard")).click();
    assertThat(driver.findElement(By.linkText("Standard")).getText(), is("Standard"));
    driver.findElement(By.id("user_login")).click();
    driver.findElement(By.id("user_login")).sendKeys("libeadmin1@in.ibm.com");
    driver.findElement(By.id("user_login")).click();
    driver.findElement(By.id("new_user")).click();
    driver.findElement(By.id("user_password")).sendKeys("liberty@1234");
    assertThat(driver.findElement(By.id("new_user")).getText(), is("Username or email\\\\nPassword\\\\nForgot your password?\\\\nRemember me\\\\nSign in"));
    assertThat(driver.findElement(By.cssSelector(".js-sign-in-button")).getText(), is("Sign in"));
    driver.findElement(By.cssSelector(".js-sign-in-button")).click();
  }

	@Test
	public void bselectproject() {
    //driver.get("https://gbsgit.edst.ibm.com/");
    driver.manage().window().setSize(new Dimension(1050, 652));
    assertThat(driver.findElement(By.cssSelector(".project-row:nth-child(2) .project-name")).getText(), is("liberty-demo"));
    driver.findElement(By.cssSelector(".project-row:nth-child(2) .project-name")).click();
    js.executeScript("window.scrollTo(0,243)");
    js.executeScript("window.scrollTo(0,215)");
    js.executeScript("window.scrollTo(0,353)");
    assertThat(driver.findElement(By.cssSelector(".tree-item:nth-child(12) .position-relative:nth-child(2)")).getText(), is("Jenkinsfile"));
    driver.findElement(By.cssSelector(".tree-item:nth-child(12) .position-relative:nth-child(2)")).click();
    js.executeScript("window.scrollTo(0,0)");
  }
	@Test
	public void clogout() {
    driver.get("https://gbsgit.edst.ibm.com/");
    driver.manage().window().setSize(new Dimension(1296, 688));
    driver.findElement(By.cssSelector(".user-bar-item")).click();
    assertThat(driver.findElement(By.cssSelector(".sign-out-link > .gl-new-dropdown-item-text-wrapper")).getText(), is("Sign out"));
    driver.findElement(By.cssSelector(".sign-out-link > .gl-new-dropdown-item-text-wrapper")).click();
  }
}
