name: Build and Deploy

on: workflow_dispatch

  
jobs:
  # demo_app_authentication:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Generate a token
  #       id: generate-token
  #       uses: actions/create-github-app-token@v1
  #       with:
  #         app-id: ${{ vars.APP_ID }}
  #         private-key: ${{ secrets.PRIVATEKEY }}

      # - name: Use the token
      #   env:
      #     GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      #   run: |
      #     gh api octocat
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build and test with Maven
      run: |
       mvn spring-javaformat:apply
       mvn -B package -Pcoverage
      

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-jar
        path: target/*.jar

    - name: Generate JaCoCo badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2
      with:
        badges-directory: badges
        generate-branches-badge: true
        generate-summary: true

    - name: Log coverage percentages to workflow output
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branches = ${{ steps.jacoco.outputs.branches }}"

    - name: Upload JaCoCo coverage report as a workflow artifact
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report
        path: target/site/jacoco/


    - name: Comment on PR with coverage percentages
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        REPORT=$(<badges/coverage-summary.json)
        COVERAGE=$(jq -r '.coverage' <<< "$REPORT")%
        BRANCHES=$(jq -r '.branches' <<< "$REPORT")%
        NEWLINE=$'\n'
        BODY="## JaCoCo Test Coverage Summary Statistics${NEWLINE}* __Coverage:__ ${COVERAGE}${NEWLINE}* __Branches:__ ${BRANCHES}"
        gh pr comment ${{github.event.pull_request.number}} -b "${BODY}"
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Get the Coverage info
      run: |
        echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
        echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"

  
  SAST-Scan:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      

    - name: sast-scan
      uses: AppThreat/sast-scan-action@v1.0.0
      with:
       output: reports
       type: java
    - name: Upload scan reports
      uses: actions/upload-artifact@v1.0.0
      with:
       name: sast-scan-reports
       path: reports 
    

  docker-build:
      runs-on: ubuntu-latest
      needs: SAST-Scan
      steps:
       - name: Checkout code
         uses: actions/checkout@v2
         
       - name: Download JAR artifact
         uses: actions/download-artifact@v2
         with:
          name: app-jar
          path: target/*.jar

       - name: docker login
         uses: docker/login-action@v1
         with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

       - name: Build and push Docker image
         uses: docker/build-push-action@v2
         with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ruth99/github-actions-pet-clinic:${{ github.sha }}

  
  ocp-deploy:
      runs-on: ubuntu-latest
      needs: docker-build
      steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: deployment
         run: |
          oc version
          oc login --token=${{ secrets.OCP_TOKEN }} --server=${{ vars.OCP_URL }}
          oc whoami
          oc project ${{ vars.OCP_PROJECT }}
          cd deploy
          ls -la
          helm ls -n ruth
          helm upgrade --install test-actions -f values.yaml --set image.tag=${{ github.sha }} . -n ${{ vars.OCP_PROJECT }}
          


         

 
     
    

   
          
          
        

  
