name: docker-build

on: workflow_dispatch

  
jobs:
  
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        maven: 3.9.0

    - name: Build and test with Maven
      run: |
       mvn spring-javaformat:apply
       mvn package -Pcoverage
      
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v2
      with:
        path: target/*.jar 
    

  docker-build:
      runs-on: ubuntu-latest
      needs: build_and_test
      steps:
       - name: Checkout code
         uses: actions/checkout@v2
         
       - name: Download JAR artifact
         uses: actions/download-artifact@v2
         with:
          path: target/*.jar

       - name: docker login
         uses: docker/login-action@v1
         with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

       - name: Build and push Docker image
         uses: docker/build-push-action@v2
         with:
          context: .
          file: Dockerfile
          push: true
          tags: ruth99/github-actions-pet-clinic:${{ github.sha }}

  
  
         
 
